# Isolate research outputs produced during instrumentation from the empirical repo.
original <- normalizePath('.')
.libPaths(c(file.path(original,'.R-library'),.libPaths()))
dir.create('.cache',showWarnings=FALSE)
scratch <- tempfile('r-coverage-',tmpdir=file.path(original,'.cache'))
dir.create(scratch);dir.create(file.path(scratch,'scripts'))
file.copy('scripts/did.R',file.path(scratch,'scripts/did.R'))
file.copy('scripts/test_did_calls.R',file.path(scratch,'scripts/test_did_calls.R'))
file.symlink(file.path(original,'.R-library'),file.path(scratch,'.R-library'))
setwd(scratch)
# Instrument the original R script and assert aggregate acceptance contracts.
.libPaths(c(normalizePath('.R-library'),.libPaths()))
coverage <- covr::file_coverage('scripts/did.R','scripts/test_did_calls.R')
pct <- covr::percent_coverage(coverage)
write.csv(data.frame(component='R DiD analysis',coverage=pct),'results/r_coverage.csv',row.names=FALSE)
stopifnot(pct>=90)
mc <- read.csv('results/did_monte_carlo.csv')
stopifnot(nrow(mc)==3,all(mc$repetitions==100))
p <- read.csv('results/mpdta_estimates.csv')
stopifnot(nrow(p)==2,all(p$se>0),all(p$lo95<p$hi95))
d <- read.csv('results/bacon.csv')
stopifnot(abs(sum(d$weight)-1)<1e-6,abs(sum(d$weight*d$estimate)-p$estimate[p$method=='TWFE'])<1e-6)
cat('R coverage',pct,'and independent accounting checks passed\n')

file.copy('results/r_coverage.csv',file.path(original,'results/r_coverage.csv'),overwrite=TRUE)
setwd(original)
